# Last updated: 2026-02-21
"""
EOS (Exhaustion of Strength) Strategy Engine
Generates trading signals based on EOS strategy rules.
Ensures proper trades are taken from Dhan API data.
"""

from datetime import datetime, time as dt_time, timedelta
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field
from enum import Enum

from .config import EOS_CONFIG, FNO_STOCKS
from .data_fetcher import EOSDataFetcher


class SignalType(Enum):
    """Type of trading signal."""
    NO_SIGNAL = "NO_SIGNAL"
    BUY_PUT = "BUY_PUT"      # Bearish signal - price went up, expect reversal
    BUY_CALL = "BUY_CALL"    # Bullish signal - price went down, expect reversal


class ExitReason(Enum):
    """Reason for exiting a position."""
    INITIAL_STOP_LOSS = "INITIAL_STOP_LOSS"
    TRAILING_STOP_LOSS = "TRAILING_STOP_LOSS"
    SMA_CROSSOVER = "SMA_CROSSOVER"
    TIME_EXIT = "TIME_EXIT"
    MAX_LOSS_DAY = "MAX_LOSS_DAY"


@dataclass
class Position:
    """Represents an open position."""
    symbol: str
    option_type: str          # "CALL" or "PUT"
    strike_price: float
    entry_price: float
    entry_time: datetime
    quantity: int             # Number of lots * lot_size
    lot_size: int
    initial_stop_loss: float  # 30% below entry
    current_stop_loss: float  # Updated with trailing
    highest_price: float      # For trailing SL calculation
    security_id: int          # Option security ID for tracking
    
    def __post_init__(self):
        self.initial_stop_loss = self.entry_price * (1 - EOS_CONFIG["initial_stop_loss_pct"] / 100)
        self.current_stop_loss = self.initial_stop_loss
        self.highest_price = self.entry_price


@dataclass
class Signal:
    """Trading signal generated by the strategy."""
    symbol: str
    signal_type: SignalType
    timestamp: datetime
    spot_price: float
    prev_close: float
    price_change_pct: float
    current_oi: int
    prev_oi: int
    oi_change_pct: float
    recommended_strike: float
    recommended_expiry: str
    sma_fast: float
    sma_slow: float
    confidence: str           # "HIGH", "MEDIUM", "LOW"
    notes: str = ""


class EOSStrategyEngine:
    """
    EOS Strategy Engine - Generates entry and exit signals.
    
    Entry Conditions:
    1. Price change > 2% from previous day close
    2. OI change > 1.75% from previous day close
    3. SMA alignment check (8-SMA and 20-SMA on futures)
    
    Exit Conditions:
    1. Initial Stop Loss: 30% of option price
    2. Trailing Stop Loss: ₹10 for every ₹10 move
    3. SMA Crossover (after 1 hour from entry)
    4. Time-based exit at 3:18 PM
    """
    
    def __init__(self, data_fetcher: EOSDataFetcher = None):
        self.data_fetcher = data_fetcher or EOSDataFetcher()
        self.positions: Dict[str, Position] = {}  # symbol -> Position
        self.daily_pnl: float = 0.0
        self.trades_today: int = 0
        self.traded_symbols_today: set = set()  # No re-entry
        self.config = EOS_CONFIG
    
    def reset_daily_state(self):
        """Reset daily tracking variables. Call at start of each trading day."""
        self.daily_pnl = 0.0
        self.trades_today = 0
        self.traded_symbols_today = set()
    
    def is_market_hours(self, current_time: datetime = None) -> bool:
        """Check if current time is within market hours."""
        if current_time is None:
            current_time = datetime.now()
        
        market_open = dt_time(9, 15)
        market_close = dt_time(15, 30)
        current = current_time.time()
        
        return market_open <= current <= market_close
    
    def can_take_new_trade(self, symbol: str) -> Tuple[bool, str]:
        """
        Check if we can take a new trade.
        Returns (can_trade, reason_if_not)
        """
        # Check max trades per day
        if self.trades_today >= self.config["max_trades_per_day"]:
            return False, f"Max trades ({self.config['max_trades_per_day']}) reached for today"
        
        # Check max loss per day
        if self.daily_pnl <= -self.config["max_loss_per_day"]:
            return False, f"Max daily loss (₹{self.config['max_loss_per_day']}) reached"
        
        # Check if already traded this symbol (no re-entry)
        if not self.config["allow_reentry"] and symbol in self.traded_symbols_today:
            return False, f"Already traded {symbol} today (no re-entry allowed)"
        
        # Check if position already exists
        if symbol in self.positions:
            return False, f"Position already open for {symbol}"

        return True, "OK"

    def check_entry_conditions(self, symbol: str, current_price: float, prev_close: float,
                                current_oi: int, prev_oi: int,
                                futures_prices: List[float]) -> Tuple[bool, SignalType, Dict]:
        """
        Check if entry conditions are met for EOS strategy.

        Args:
            symbol: Stock symbol
            current_price: Current spot price
            prev_close: Previous day's closing price
            current_oi: Current Open Interest
            prev_oi: Previous day's closing OI
            futures_prices: List of futures close prices for SMA calculation

        Returns:
            Tuple of (conditions_met, signal_type, details_dict)
        """
        details = {
            "price_change_pct": 0.0,
            "oi_change_pct": 0.0,
            "sma_fast": None,
            "sma_slow": None,
            "sma_aligned": False,
            "conditions_met": []
        }

        # Calculate price change
        price_change_pct = self.data_fetcher.calculate_price_change_pct(current_price, prev_close)
        details["price_change_pct"] = price_change_pct

        # Calculate OI change
        oi_change_pct = self.data_fetcher.calculate_oi_change_pct(current_oi, prev_oi)
        details["oi_change_pct"] = oi_change_pct

        # Calculate SMAs on futures price
        sma_fast = self.data_fetcher.calculate_sma(futures_prices, self.config["sma_fast"])
        sma_slow = self.data_fetcher.calculate_sma(futures_prices, self.config["sma_slow"])
        details["sma_fast"] = sma_fast
        details["sma_slow"] = sma_slow

        # Check conditions
        # 1. Price change > threshold (absolute value for both directions)
        price_condition = abs(price_change_pct) > self.config["price_change_threshold"]
        if price_condition:
            details["conditions_met"].append("PRICE_CHANGE")

        # 2. OI change > threshold
        oi_condition = abs(oi_change_pct) > self.config["oi_change_threshold"]
        if oi_condition:
            details["conditions_met"].append("OI_CHANGE")

        # 3. SMA alignment (optional for entry, required for exit)
        if sma_fast and sma_slow:
            details["sma_aligned"] = True
            details["conditions_met"].append("SMA_AVAILABLE")

        # Determine signal type based on price direction
        # If price went UP strongly, we expect reversal -> BUY PUT
        # If price went DOWN strongly, we expect reversal -> BUY CALL
        if price_condition and oi_condition:
            if price_change_pct > self.config["price_change_threshold"]:
                return True, SignalType.BUY_PUT, details
            elif price_change_pct < -self.config["price_change_threshold"]:
                return True, SignalType.BUY_CALL, details

        return False, SignalType.NO_SIGNAL, details

    def generate_entry_signal(self, symbol: str) -> Optional[Signal]:
        """
        Generate entry signal for a symbol if conditions are met.

        Args:
            symbol: Stock symbol to analyze

        Returns:
            Signal object if entry conditions met, None otherwise
        """
        # Check if we can take new trade
        can_trade, reason = self.can_take_new_trade(symbol)
        if not can_trade:
            return None

        # Get all required data
        stock_data = self.data_fetcher.get_stock_data_for_screening(symbol)
        if stock_data.get("status") != "success":
            return None

        # Extract data from responses
        quote = stock_data.get("quote", {})
        if quote.get("status") != "success":
            return None

        # Get current price and previous close from quote
        quote_data = quote.get("data", [])
        if not quote_data:
            return None

        instrument_data = quote_data[0] if isinstance(quote_data, list) else quote_data
        current_price = instrument_data.get("LTP", 0)
        prev_close = instrument_data.get("close", instrument_data.get("prevClose", 0))

        # Get OI from option chain (sum of all strikes for current month)
        option_chain = stock_data.get("option_chain", {})
        current_oi = 0
        prev_oi = 0
        if option_chain.get("status") == "success":
            for item in option_chain.get("data", []):
                current_oi += item.get("oi", 0)
                prev_oi += item.get("previous_oi", item.get("prevOI", 0))

        # Get futures prices for SMA
        futures_data = stock_data.get("futures_data", {})
        futures_prices = []
        if futures_data.get("status") == "success":
            candles = futures_data.get("data", [])
            futures_prices = [c.get("close", 0) for c in candles if c.get("close")]

        # Check entry conditions
        conditions_met, signal_type, details = self.check_entry_conditions(
            symbol, current_price, prev_close, current_oi, prev_oi, futures_prices
        )

        if not conditions_met:
            return None

        # Get recommended strike and expiry
        expiry_list = stock_data.get("expiry_list", {})
        monthly_expiry = self.data_fetcher.get_monthly_expiry(expiry_list)

        option_type = "PUT" if signal_type == SignalType.BUY_PUT else "CALL"
        nearest_otm = self.data_fetcher.find_nearest_otm_strike(
            current_price, option_chain, option_type
        )
        recommended_strike = nearest_otm.get("strikePrice", 0) if nearest_otm else 0

        # Create signal
        return Signal(
            symbol=symbol,
            signal_type=signal_type,
            timestamp=datetime.now(),
            spot_price=current_price,
            prev_close=prev_close,
            price_change_pct=details["price_change_pct"],
            current_oi=current_oi,
            prev_oi=prev_oi,
            oi_change_pct=details["oi_change_pct"],
            recommended_strike=recommended_strike,
            recommended_expiry=monthly_expiry or "",
            sma_fast=details["sma_fast"] or 0,
            sma_slow=details["sma_slow"] or 0,
            confidence="HIGH" if len(details["conditions_met"]) >= 3 else "MEDIUM",
            notes=f"Conditions: {', '.join(details['conditions_met'])}"
        )

    def update_trailing_stop_loss(self, position: Position, current_price: float) -> float:
        """
        Update trailing stop loss for a position.
        Trail by ₹10 for every ₹10 move in profit.

        Args:
            position: Current position
            current_price: Current option price

        Returns:
            Updated stop loss price
        """
        trigger = self.config["trailing_sl_trigger"]
        trail_amount = self.config["trailing_sl_amount"]

        # Update highest price
        if current_price > position.highest_price:
            position.highest_price = current_price

        # Calculate profit from entry
        profit = current_price - position.entry_price

        # If profit >= trigger, start trailing
        if profit >= trigger:
            # Calculate how many times we've moved by trigger amount
            trail_steps = int(profit / trigger)
            new_sl = position.entry_price + (trail_steps * trail_amount) - trail_amount

            # Only update if new SL is higher than current
            if new_sl > position.current_stop_loss:
                position.current_stop_loss = new_sl

        return position.current_stop_loss

    def check_exit_conditions(self, position: Position, current_price: float,
                               futures_prices: List[float],
                               current_time: datetime = None) -> Tuple[bool, Optional[ExitReason]]:
        """
        Check if exit conditions are met for a position.

        Args:
            position: Current position
            current_price: Current option price
            futures_prices: List of futures close prices for SMA
            current_time: Current timestamp

        Returns:
            Tuple of (should_exit, exit_reason)
        """
        if current_time is None:
            current_time = datetime.now()

        # 1. Check Initial Stop Loss (always active)
        if current_price <= position.initial_stop_loss:
            return True, ExitReason.INITIAL_STOP_LOSS

        # 2. Check Trailing Stop Loss (always active after first profit)
        self.update_trailing_stop_loss(position, current_price)
        if current_price <= position.current_stop_loss and position.current_stop_loss > position.initial_stop_loss:
            return True, ExitReason.TRAILING_STOP_LOSS

        # 3. Check Time-based exit (3:18 PM)
        final_exit = dt_time(15, 18)
        if current_time.time() >= final_exit:
            return True, ExitReason.TIME_EXIT

        # 4. Check SMA Crossover (only after 1 hour from entry)
        time_in_trade = (current_time - position.entry_time).total_seconds() / 60
        if time_in_trade >= self.config["sma_active_after_minutes"]:
            sma_fast = self.data_fetcher.calculate_sma(futures_prices, self.config["sma_fast"])
            sma_slow = self.data_fetcher.calculate_sma(futures_prices, self.config["sma_slow"])

            if sma_fast and sma_slow:
                # For PUT position, exit if fast SMA crosses above slow (bullish reversal)
                # For CALL position, exit if fast SMA crosses below slow (bearish reversal)
                if position.option_type == "PUT" and sma_fast > sma_slow:
                    return True, ExitReason.SMA_CROSSOVER
                elif position.option_type == "CALL" and sma_fast < sma_slow:
                    return True, ExitReason.SMA_CROSSOVER

        return False, None

    def open_position(self, signal: Signal, option_price: float, security_id: int) -> Position:
        """
        Open a new position based on a signal.

        Args:
            signal: Entry signal
            option_price: Option entry price
            security_id: Option security ID

        Returns:
            Position object
        """
        stock_info = FNO_STOCKS.get(signal.symbol, {})
        lot_size = stock_info.get("lot_size", 1)
        lots = self.config["lots_per_trade"]

        position = Position(
            symbol=signal.symbol,
            option_type="PUT" if signal.signal_type == SignalType.BUY_PUT else "CALL",
            strike_price=signal.recommended_strike,
            entry_price=option_price,
            entry_time=signal.timestamp,
            quantity=lots * lot_size,
            lot_size=lot_size,
            initial_stop_loss=option_price * (1 - self.config["initial_stop_loss_pct"] / 100),
            current_stop_loss=option_price * (1 - self.config["initial_stop_loss_pct"] / 100),
            highest_price=option_price,
            security_id=security_id
        )

        self.positions[signal.symbol] = position
        self.trades_today += 1
        self.traded_symbols_today.add(signal.symbol)

        return position

    def close_position(self, symbol: str, exit_price: float, exit_reason: ExitReason) -> Dict:
        """
        Close a position and calculate PnL.

        Args:
            symbol: Stock symbol
            exit_price: Exit price of option
            exit_reason: Reason for exit

        Returns:
            Dict with trade summary
        """
        if symbol not in self.positions:
            return {"status": "error", "error": f"No position found for {symbol}"}

        position = self.positions[symbol]
        pnl = (exit_price - position.entry_price) * position.quantity
        pnl_pct = ((exit_price - position.entry_price) / position.entry_price) * 100

        self.daily_pnl += pnl
        del self.positions[symbol]

        return {
            "status": "success",
            "symbol": symbol,
            "option_type": position.option_type,
            "strike_price": position.strike_price,
            "entry_price": position.entry_price,
            "exit_price": exit_price,
            "quantity": position.quantity,
            "pnl": pnl,
            "pnl_pct": pnl_pct,
            "exit_reason": exit_reason.value,
            "entry_time": position.entry_time.isoformat(),
            "exit_time": datetime.now().isoformat(),
            "hold_duration_minutes": (datetime.now() - position.entry_time).total_seconds() / 60
        }

    def scan_all_stocks(self) -> List[Signal]:
        """
        Scan all FNO stocks for entry signals.

        Returns:
            List of Signal objects for stocks meeting entry conditions
        """
        signals = []

        for symbol in FNO_STOCKS.keys():
            if symbol in self.traded_symbols_today and not self.config["allow_reentry"]:
                continue

            signal = self.generate_entry_signal(symbol)
            if signal:
                signals.append(signal)

        # Sort by confidence and absolute price change
        signals.sort(key=lambda s: (s.confidence, abs(s.price_change_pct)), reverse=True)

        return signals

    def get_portfolio_status(self) -> Dict:
        """Get current portfolio status."""
        return {
            "open_positions": len(self.positions),
            "positions": {
                sym: {
                    "option_type": pos.option_type,
                    "strike": pos.strike_price,
                    "entry_price": pos.entry_price,
                    "current_sl": pos.current_stop_loss,
                    "quantity": pos.quantity
                }
                for sym, pos in self.positions.items()
            },
            "daily_pnl": self.daily_pnl,
            "trades_today": self.trades_today,
            "max_trades": self.config["max_trades_per_day"],
            "max_loss_remaining": self.config["max_loss_per_day"] + self.daily_pnl
        }

